CREATE TABLE [dbo].[Names]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Names] ADD CONSTRAINT [PK_Names] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
